version: "2"

services:
  pm:
    image: aiotrc/pm
    environment:
      - PORT=8080
      - ADDR=0.0.0.0
      - D_HOST=172.17.0.1
      - DB_URL=mongodb://172.17.0.1:27017
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
