version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

networks:
  default:
    external:
      name: i1820
