---
version: "3"

services:
  loraserver:
    image: loraserver/loraserver:1
    restart: always
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  appserver:
    image: loraserver/lora-app-server:1
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  gatewaybridge:
    image: loraserver/lora-gateway-bridge:2
    restart: always
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge

  postgresql:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - 5432
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    ports:
      - 6379
    image: redis:4-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
